<?php

use Illuminate\Database\Seeder;

class TimezoneTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('timezone')->insert([
        		['name' => '(GMT-11:00) International Date Line West', 'value' => 'Pacific/Kwajalein'],
        		['name' => '(GMT-11:00) Midway Island', 'value' => 'Pacific/Midway'],
        		['name' => '(GMT-11:00) Samoa', 'value' => 'Pacific/Samoa'],
        		['name' => '(GMT-10:00) Hawaii', 'value' => 'Pacific/Honolulu'],
        		['name' => '(GMT-10:00) Pacific/Honolulu', 'value' => 'Pacific/Honolulu'],
        		['name' => '(GMT-09:00) Alaska', 'value' => 'US/Alaska'],
        		['name' => '(GMT-08:00) America/Los_Angeles', 'value' => 'America/Los_Angeles'],
        		['name' => '(GMT-08:00) Pacific Time (US &amp; Canada)', 'value' => 'America/Los_Angeles'],
        		['name' => '(GMT-08:00) Tijuana', 'value' => 'America/Tijuana'],
        		['name' => '(GMT-07:00) America/Denver', 'value' => 'America/Denver'],
        		['name' => '(GMT-07:00) America/Phoenix', 'value' => 'America/Phoenix'],
        		['name' => '(GMT-07:00) Arizona', 'value' => 'US/Arizona'],
        		['name' => '(GMT-07:00) Chihuahua', 'value' => 'America/Chihuahua'],
        		['name' => '(GMT-07:00) Mazatlan', 'value' => 'America/Mazatlan'],
        		['name' => '(GMT-07:00) Mountain Time (US &amp; Canada)', 'value' => 'US/Mountain'],
        		['name' => '(GMT-06:00) America/Chicago', 'value' => 'America/Chicago'],
        		['name' => '(GMT-06:00) America/Mexico_City', 'value' => 'America/Mexico_City'],
        		['name' => '(GMT-06:00) Central America', 'value' => 'America/Managua'],
        		['name' => '(GMT-06:00) Central Time (US &amp; Canada)', 'value' => 'US/Central'],
        		['name' => '(GMT-06:00) Guadalajara', 'value' => 'America/Mexico_City'],
        		['name' => '(GMT-06:00) Mexico City', 'value' => 'America/Mexico_City'],
        		['name' => '(GMT-06:00) Monterrey', 'value' => 'America/Monterrey'],
        		['name' => '(GMT-06:00) Saskatchewan', 'value' => 'Canada/Saskatchewan'],
        		['name' => '(GMT-05:00) America/Nassau', 'value' => 'America/Nassau'],
        		['name' => '(GMT-05:00) America/New_York', 'value' => 'America/New_York'],
        		['name' => '(GMT-05:00) America/Port-au-Prince', 'value' => 'America/Port-au-Prince'],
        		['name' => '(GMT-05:00) America/Toronto', 'value' => 'America/Toronto'],
        		['name' => '(GMT-05:00) Bogota', 'value' => 'America/Bogota'],
        		['name' => '(GMT-05:00) Eastern Time (US &amp; Canada)', 'value' => 'US/Eastern'],
        		['name' => '(GMT-05:00) Indiana (East)', 'value' => 'US/East-Indiana'],
        		['name' => '(GMT-05:00) Lima', 'value' => 'America/Lima'],
        		['name' => '(GMT-05:00) Quito', 'value' => 'America/Bogota'],
        		['name' => '(GMT-04:30) Caracas', 'value' => 'America/Caracas'],
        		['name' => '(GMT-04:00) Atlantic Time (Canada)', 'value' => 'Canada/Atlantic'],
        		['name' => '(GMT-04:00) Georgetown', 'value' => 'America/Argentina/Buenos_Aires'],
        		['name' => '(GMT-04:00) La Paz', 'value' => 'America/La_Paz'],
        		['name' => '(GMT-03:30) Newfoundland', 'value' => 'Canada/Newfoundland'],
        		['name' => '(GMT-03:00) America/Argentina/Buenos_Aires', 'value' => 'America/Argentina/Buenos_Aires'],
        		['name' => '(GMT-03:00) America/Cordoba', 'value' => 'America/Cordoba'],
        		['name' => '(GMT-03:00) America/Fortaleza', 'value' => 'America/Fortaleza'],
        		['name' => '(GMT-03:00) America/Montevideo', 'value' => 'America/Montevideo'],
        		['name' => '(GMT-03:00) America/Santiago', 'value' => 'America/Santiago'],
        		['name' => '(GMT-03:00) America/Sao_Paulo', 'value' => 'America/Sao_Paulo'],
        		['name' => '(GMT-03:00) Brasilia', 'value' => 'America/Sao_Paulo'],
        		['name' => '(GMT-03:00) Buenos Aires', 'value' => 'America/Argentina/Buenos_Aires'],
        		['name' => '(GMT-03:00) Greenland', 'value' => 'America/Godthab'],
        		['name' => '(GMT-03:00) Santiago', 'value' => 'America/Santiago'],
        		['name' => '(GMT-02:00) Mid-Atlantic', 'value' => 'America/Noronha'],
        		['name' => '(GMT-01:00) Azores', 'value' => 'Atlantic/Azores'],
        		['name' => '(GMT-01:00) Cape Verde Is.', 'value' => 'Atlantic/Cape_Verde'],
        		['name' => '(GMT+00:00) Africa/Casablanca', 'value' => 'Africa/Casablanca'],
        		['name' => '(GMT+00:00) Atlantic/Canary', 'value' => 'Atlantic/Canary'],
        		['name' => '(GMT+00:00) Atlantic/Reykjavik', 'value' => 'Atlantic/Reykjavik'],
        		['name' => '(GMT+00:00) Casablanca', 'value' => 'Africa/Casablanca'],
        		['name' => '(GMT+00:00) Dublin', 'value' => 'Etc/Greenwich'],
        		['name' => '(GMT+00:00) Edinburgh', 'value' => 'Europe/London'],
        		['name' => '(GMT+00:00) Europe/Dublin', 'value' => 'Europe/Dublin'],
        		['name' => '(GMT+00:00) Europe/Lisbon', 'value' => 'Europe/Lisbon'],
        		['name' => '(GMT+00:00) Europe/London', 'value' => 'Europe/London'],
        		['name' => '(GMT+00:00) Lisbon', 'value' => 'Europe/Lisbon'],
        		['name' => '(GMT+00:00) London', 'value' => 'Europe/London'],
        		['name' => '(GMT+00:00) Monrovia', 'value' => 'Africa/Monrovia'],
        		['name' => '(GMT+00:00) UTC', 'value' => 'UTC'],
        		['name' => '(GMT+01:00) Amsterdam', 'value' => 'Europe/Amsterdam'],
        		['name' => '(GMT+01:00) Belgrade', 'value' => 'Europe/Belgrade'],
        		['name' => '(GMT+01:00) Berlin', 'value' => 'Europe/Berlin'],
        		['name' => '(GMT+01:00) Bern', 'value' => 'Europe/Berlin'],
        		['name' => '(GMT+01:00) Bratislava', 'value' => 'Europe/Bratislava'],
        		['name' => '(GMT+01:00) Brussels', 'value' => 'Europe/Brussels'],
        		['name' => '(GMT+01:00) Budapest', 'value' => 'Europe/Budapest'],
        		['name' => '(GMT+01:00) Copenhagen', 'value' => 'Europe/Copenhagen'],
        		['name' => '(GMT+01:00) Europe/Amsterdam', 'value' => 'Europe/Amsterdam'],
        		['name' => '(GMT+01:00) Europe/Belgrade', 'value' => 'Europe/Belgrade'],
        		['name' => '(GMT+01:00) Europe/Berlin', 'value' => 'Europe/Berlin'],
        		['name' => '(GMT+01:00) Europe/Bratislava', 'value' => 'Europe/Bratislava'],
        		['name' => '(GMT+01:00) Europe/Brussels', 'value' => 'Europe/Brussels'],
        		['name' => '(GMT+01:00) Europe/Budapest', 'value' => 'Europe/Budapest'],
				['name' => '(GMT+01:00) Europe/Copenhagen', 'value' => 'Europe/Copenhagen'],
				['name' => '(GMT+01:00) Europe/Ljubljana', 'value' => 'Europe/Ljubljana'],
				['name' => '(GMT+01:00) Europe/Madrid', 'value' => 'Europe/Madrid'],
				['name' => '(GMT+01:00) Europe/Monaco', 'value' => 'Europe/Monaco'],
				['name' => '(GMT+01:00) Europe/Oslo', 'value' => 'Europe/Oslo'],
				['name' => '(GMT+01:00) Europe/Paris', 'value' => 'Europe/Paris'],
				['name' => '(GMT+01:00) Europe/Podgorica', 'value' => 'Europe/Podgorica'],
				['name' => '(GMT+01:00) Europe/Prague', 'value' => 'Europe/Prague'],
				['name' => '(GMT+01:00) Europe/Rome', 'value' => 'Europe/Rome'],
				['name' => '(GMT+01:00) Europe/Stockholm', 'value' => 'Europe/Stockholm'],
				['name' => '(GMT+01:00) Europe/Tirane', 'value' => 'Europe/Tirane'],
				['name' => '(GMT+01:00) Europe/Vienna', 'value' => 'Europe/Vienna'],
				['name' => '(GMT+01:00) Europe/Warsaw', 'value' => 'Europe/Warsaw'],
				['name' => '(GMT+01:00) Europe/Zagreb', 'value' => 'Europe/Zagreb'],
				['name' => '(GMT+01:00) Europe/Zurich', 'value' => 'Europe/Zurich'],
				['name' => '(GMT+01:00) Ljubljana', 'value' => 'Europe/Ljubljana'],
				['name' => '(GMT+01:00) Madrid', 'value' => 'Europe/Madrid'],
				['name' => '(GMT+01:00) Paris', 'value' => 'Europe/Paris'],
				['name' => '(GMT+01:00) Prague', 'value' => 'Europe/Prague'],
				['name' => '(GMT+01:00) Rome', 'value' => 'Europe/Rome'],
				['name' => '(GMT+01:00) Sarajevo', 'value' => 'Europe/Sarajevo'],
				['name' => '(GMT+01:00) Skopje', 'value' => 'Europe/Skopje'],
				['name' => '(GMT+01:00) Stockholm', 'value' => 'Europe/Stockholm'],
				['name' => '(GMT+01:00) Vienna', 'value' => 'Europe/Vienna'],
				['name' => '(GMT+01:00) Warsaw', 'value' => 'Europe/Warsaw'],
				['name' => '(GMT+01:00) West Central Africa', 'value' => 'Africa/Lagos'],
				['name' => '(GMT+01:00) Zagreb', 'value' => 'Europe/Zagreb'],
				['name' => '(GMT+02:00) Asia/Beirut', 'value' => 'Asia/Beirut'],
				['name' => '(GMT+02:00) Asia/Jerusalem', 'value' => 'Asia/Jerusalem'],
				['name' => '(GMT+02:00) Asia/Nicosia', 'value' => 'Asia/Nicosia'],
				['name' => '(GMT+02:00) Athens', 'value' => 'Europe/Athens'],
				['name' => '(GMT+02:00) Bucharest', 'value' => 'Europe/Bucharest'],
				['name' => '(GMT+02:00) Cairo', 'value' => 'Africa/Cairo'],
				['name' => '(GMT+02:00) Europe/Athens', 'value' => 'Europe/Athens'],
				['name' => '(GMT+02:00) Europe/Helsinki', 'value' => 'Europe/Helsinki'],
				['name' => '(GMT+02:00) Europe/Istanbul', 'value' => 'Europe/Istanbul'],
				['name' => '(GMT+02:00) Europe/Riga', 'value' => 'Europe/Riga'],
				['name' => '(GMT+02:00) Europe/Sofia', 'value' => 'Europe/Sofia'],
				['name' => '(GMT+02:00) Harare', 'value' => 'Africa/Harare'],
				['name' => '(GMT+02:00) Helsinki', 'value' => 'Europe/Helsinki'],
				['name' => '(GMT+02:00) Istanbul', 'value' => 'Europe/Istanbul'],
				['name' => '(GMT+02:00) Jerusalem', 'value' => 'Asia/Jerusalem'],
				['name' => '(GMT+02:00) Kyiv', 'value' => 'Europe/Helsinki'],
				['name' => '(GMT+02:00) Pretoria', 'value' => 'Africa/Johannesburg'],
				['name' => '(GMT+02:00) Riga', 'value' => 'Europe/Riga'],
				['name' => '(GMT+02:00) Sofia', 'value' => 'Europe/Sofia'],
				['name' => '(GMT+02:00) Tallinn', 'value' => 'Europe/Tallinn'],
				['name' => '(GMT+02:00) Vilnius', 'value' => 'Europe/Vilnius'],
				['name' => '(GMT+03:00) Baghdad', 'value' => 'Asia/Baghdad'],
				['name' => '(GMT+03:00) Europe/Minsk', 'value' => 'Europe/Minsk'],
				['name' => '(GMT+03:00) Europe/Moscow', 'value' => 'Europe/Moscow'],
				['name' => '(GMT+03:00) Kuwait', 'value' => 'Asia/Kuwait'],
				['name' => '(GMT+03:00) Minsk', 'value' => 'Europe/Minsk'],
				['name' => '(GMT+03:00) Moscow', 'value' => 'Europe/Moscow'],
				['name' => '(GMT+03:00) Nairobi', 'value' => 'Africa/Nairobi'],
				['name' => '(GMT+03:00) Riyadh', 'value' => 'Asia/Riyadh'],
				['name' => '(GMT+03:00) St. Petersburg', 'value' => 'Europe/Moscow'],
				['name' => '(GMT+03:00) Volgograd', 'value' => 'Europe/Volgograd'],
				['name' => '(GMT+03:30) Tehran', 'value' => 'Asia/Tehran'],
				['name' => '(GMT+04:00) Abu Dhabi', 'value' => 'Asia/Muscat'],
				['name' => '(GMT+04:00) Asia/Dubai', 'value' => 'Asia/Dubai'],
				['name' => '(GMT+04:00) Asia/Tbilisi', 'value' => 'Asia/Tbilisi'],
				['name' => '(GMT+04:00) Baku', 'value' => 'Asia/Baku'],
				['name' => '(GMT+04:00) Muscat', 'value' => 'Asia/Muscat'],
				['name' => '(GMT+04:00) Tbilisi', 'value' => 'Asia/Tbilisi'],
				['name' => '(GMT+04:00) Yerevan', 'value' => 'Asia/Yerevan'],
				['name' => '(GMT+04:30) Kabul', 'value' => 'Asia/Kabul'],
				['name' => '(GMT+05:00) Ekaterinburg', 'value' => 'Asia/Yekaterinburg'],
				['name' => '(GMT+05:00) Indian/Maldives', 'value' => 'Indian/Maldives'],
				['name' => '(GMT+05:00) Islamabad', 'value' => 'Asia/Karachi'],
				['name' => '(GMT+05:00) Karachi', 'value' => 'Asia/Karachi'],
				['name' => '(GMT+05:00) Tashkent', 'value' => 'Asia/Tashkent'],
				['name' => '(GMT+05:30) Asia/Calcutta', 'value' => 'Asia/Calcutta'],
				['name' => '(GMT+05:30) Asia/Colombo', 'value' => 'Asia/Colombo'],
				['name' => '(GMT+05:30) Chennai', 'value' => 'Asia/Calcutta'],
				['name' => '(GMT+05:30) Kolkata', 'value' => 'Asia/Kolkata'],
				['name' => '(GMT+05:30) Mumbai', 'value' => 'Asia/Calcutta'],
				['name' => '(GMT+05:30) New Delhi', 'value' => 'Asia/Calcutta'],
				['name' => '(GMT+05:30) Sri Jayawardenepura', 'value' => 'Asia/Calcutta'],
				['name' => '(GMT+05:45) Kathmandu', 'value' => 'Asia/Katmandu'],
				['name' => '(GMT+06:00) Almaty', 'value' => 'Asia/Almaty'],
				['name' => '(GMT+06:00) Astana', 'value' => 'Asia/Dhaka'],
				['name' => '(GMT+06:00) Dhaka', 'value' => 'Asia/Dhaka'],
				['name' => '(GMT+06:00) Novosibirsk', 'value' => 'Asia/Novosibirsk'],
				['name' => '(GMT+06:00) Urumqi', 'value' => 'Asia/Urumqi'],
				['name' => '(GMT+06:30) Rangoon', 'value' => 'Asia/Rangoon'],
				['name' => '(GMT+07:00) Asia/Bangkok', 'value' => 'Asia/Bangkok'],
				['name' => '(GMT+07:00) Asia/Jakarta', 'value' => 'Asia/Jakarta'],
				['name' => '(GMT+07:00) Bangkok', 'value' => 'Asia/Bangkok'],
				['name' => '(GMT+07:00) Hanoi', 'value' => 'Asia/Bangkok'],
				['name' => '(GMT+07:00) Jakarta', 'value' => 'Asia/Jakarta'],
				['name' => '(GMT+07:00) Krasnoyarsk', 'value' => 'Asia/Krasnoyarsk'],
				['name' => '(GMT+08:00) Asia/Chongqing', 'value' => 'Asia/Chongqing'],
				['name' => '(GMT+08:00) Asia/Hong_Kong', 'value' => 'Asia/Hong_Kong'],
				['name' => '(GMT+08:00) Asia/Kuala_Lumpur', 'value' => 'Asia/Kuala_Lumpur'],
				['name' => '(GMT+08:00) Asia/Macau', 'value' => 'Asia/Macau'],
				['name' => '(GMT+08:00) Asia/Makassar', 'value' => 'Asia/Makassar'],
				['name' => '(GMT+08:00) Asia/Shanghai', 'value' => 'Asia/Shanghai'],
				['name' => '(GMT+08:00) Asia/Taipei', 'value' => 'Asia/Taipei'],
				['name' => '(GMT+08:00) Beijing', 'value' => 'Asia/Hong_Kong'],
				['name' => '(GMT+08:00) Chongqing', 'value' => 'Asia/Chongqing'],
				['name' => '(GMT+08:00) Hong Kong', 'value' => 'Asia/Hong_Kong'],
				['name' => '(GMT+08:00) Irkutsk', 'value' => 'Asia/Irkutsk'],
				['name' => '(GMT+08:00) Kuala Lumpur', 'value' => 'Asia/Kuala_Lumpur'],
				['name' => '(GMT+08:00) Perth', 'value' => 'Australia/Perth'],
				['name' => '(GMT+08:00) Singapore', 'value' => 'Asia/Singapore'],
				['name' => '(GMT+08:00) Taipei', 'value' => 'Asia/Taipei'],
				['name' => '(GMT+08:00) Ulaan Bataar', 'value' => 'Asia/Ulan_Bator'],
				['name' => '(GMT+09:00) Asia/Seoul', 'value' => 'Asia/Seoul'],
				['name' => '(GMT+09:00) Asia/Tokyo', 'value' => 'Asia/Tokyo'],
				['name' => '(GMT+09:00) Osaka', 'value' => 'Asia/Tokyo'],
				['name' => '(GMT+09:00) Sapporo', 'value' => 'Asia/Tokyo'],
				['name' => '(GMT+09:00) Seoul', 'value' => 'Asia/Seoul'],
				['name' => '(GMT+09:00) Tokyo', 'value' => 'Asia/Tokyo'],
				['name' => '(GMT+09:00) Yakutsk', 'value' => 'Asia/Yakutsk'],
				['name' => '(GMT+09:30) Adelaide', 'value' => 'Australia/Adelaide'],
				['name' => '(GMT+09:30) Darwin', 'value' => 'Australia/Darwin'],
				['name' => '(GMT+10:00) Australia/Brisbane', 'value' => 'Australia/Brisbane'],
				['name' => '(GMT+10:00) Australia/Hobart', 'value' => 'Australia/Hobart'],
				['name' => '(GMT+10:00) Australia/Melbourne', 'value' => 'Australia/Melbourne'],
				['name' => '(GMT+10:00) Australia/Sydney', 'value' => 'Australia/Sydney'],
				['name' => '(GMT+10:00) Brisbane', 'value' => 'Australia/Brisbane'],
				['name' => '(GMT+10:00) Canberra', 'value' => 'Australia/Canberra'],
				['name' => '(GMT+10:00) Guam', 'value' => 'Pacific/Guam'],
				['name' => '(GMT+10:00) Hobart', 'value' => 'Australia/Hobart'],
				['name' => '(GMT+10:00) Magadan', 'value' => 'Asia/Magadan'],
				['name' => '(GMT+10:00) Melbourne', 'value' => 'Australia/Melbourne'],
				['name' => '(GMT+10:00) Port Moresby', 'value' => 'Pacific/Port_Moresby'],
				['name' => '(GMT+10:00) Solomon Is.', 'value' => 'Asia/Magadan'],
				['name' => '(GMT+10:00) Sydney', 'value' => 'Australia/Sydney'],
				['name' => '(GMT+10:00) Vladivostok', 'value' => 'Asia/Vladivostok'],
				['name' => '(GMT+11:00) New Caledonia', 'value' => 'Asia/Magadan'],
				['name' => '(GMT+12:00) Auckland', 'value' => 'Pacific/Auckland'],
				['name' => '(GMT+12:00) Fiji', 'value' => 'Pacific/Fiji'],
				['name' => '(GMT+12:00) Kamchatka', 'value' => 'Asia/Kamchatka'],
				['name' => '(GMT+12:00) Marshall Is.', 'value' => 'Pacific/Fiji'],
				['name' => '(GMT+12:00) Pacific/Auckland', 'value' => 'Pacific/Auckland'],
				['name' => '(GMT+12:00) Wellington', 'value' => 'Pacific/Auckland'],
				['name' => '(GMT+13:00) Nuku&#39;alofa', 'value' => 'Pacific/Tongatapu'],
        	]);
    }
}
