<?php

use Illuminate\Database\Seeder;

class RoomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('rooms')->delete();
    	
        DB::table('rooms')->insert([

        		['id' => 10001 , 'user_id' => 10001, 'name' => 'Castro one-bedroom suite','sub_name' =>'Private room in San Francisco', 'summary' =>"If Im not home when you check in I''ll have a gate key taped under the gate, the front door will be unlocked, there is a picture of key location in my photos of my place.", 'property_type' =>2, 'room_type' =>2, 'accommodates' =>5, 'bedrooms' =>4, 'beds' =>4, 'bed_type' =>3, 'bathrooms' =>2.0, 'amenities' =>'1,2,5,6,9,10,12,14,21,22,23,27,28', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-06 06:31:24', 'updated_at' =>'2016-02-06 06:40:21', 'deleted_at' =>NULL],
        		['id' => 10002 , 'user_id' => 10004, 'name' => 'large, comfy br in fun neighborhood','sub_name' =>'Entire home/apt in San Francisco', 'summary' =>'large, comfortable bedroom in the heart of the mission district, the best neighborhood in san francisco! walk to awesome restaurants or bart downtown. with a park right in front and a beautiful sunny garden in back. room is for one person only.', 'property_type' =>1, 'room_type' =>1, 'accommodates' =>8, 'bedrooms' =>3, 'beds' =>4, 'bed_type' =>1, 'bathrooms' =>2.0, 'amenities' =>'3,6,7,11,12,13,15,23,24,25,28,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-06 06:47:18', 'updated_at' =>'2016-02-06 06:51:21', 'deleted_at' =>NULL],
        		['id' => 10003 , 'user_id' => 10001, 'name' => 'The city at your doorstep','sub_name' =>'Private room in San Francisco', 'summary' =>'Enjoy San Francisco city living in this centrally located Nob Hill studio apartment. Great restaurants and bars a few doors down. All you need to enjoy daily life is 1 block away, with Cable car and bus lines on the corner. Full breakfast included!', 'property_type' =>2, 'room_type' =>2, 'accommodates' =>8, 'bedrooms' =>4, 'beds' =>8, 'bed_type' =>4, 'bathrooms' =>2.0, 'amenities' =>'3,4,6,17,18,21,25,27,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Unlisted', 'created_at' =>'2016-02-08 00:32:08', 'updated_at' =>'2016-02-10 01:34:31', 'deleted_at' =>NULL],
                ['id' => 10004 , 'user_id' => 10004, 'name' => 'Charming double bedroom in Richmond','sub_name' =>'Private room in London', 'summary' =>'Charming double garden room in two bed flat with home owner. 5mins from Richmond station, Hill and town, 20 mins into Waterloo and easy access to central London.', 'property_type' =>3, 'room_type' =>2, 'accommodates' =>12, 'bedrooms' =>4, 'beds' =>5, 'bed_type' =>5, 'bathrooms' =>3.5, 'amenities' =>'1,2,10,13,22,23', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-08 01:01:08', 'updated_at' =>'2016-02-08 01:12:00', 'deleted_at' =>NULL],
                ['id' => 10005 , 'user_id' => 10001, 'name' => 'LUXURY Room','sub_name' =>'Shared room in London', 'summary' =>'Large, bright room in an AMAZING 2500 sq ft warehouse apartment in the worlds first dog food factory! Only 4 stops (6 mins) to Canary Wharf! Features a huge kitchen, luxury bathroom, 2 balconies, roof terrace, BBQ, and a full-body massage chair!', 'property_type' =>2, 'room_type' =>3, 'accommodates' =>13, 'bedrooms' =>5, 'beds' =>7, 'bed_type' =>3, 'bathrooms' =>2.0, 'amenities' =>'1,2,4,5,6,7,10,11,15,17,18,19,22,23,24,25,28,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-08 01:17:11', 'updated_at' =>'2016-02-10 01:35:02', 'deleted_at' =>NULL],
                ['id' => 10006 , 'user_id' => 10002, 'name' => 'Right by the Thames with Great View','sub_name' =>'Entire home/apt in London', 'summary' =>'Double bedroom in 4 bedroom townhouse located on the banks of the river Thames. There are fantastic views of Tower Bridge from the living room balcony. The Thames Path is 1 minute away, offering access to Tate Modern, Tower Bridge or Greenwich', 'property_type' =>1, 'room_type' =>1, 'accommodates' =>6, 'bedrooms' =>3, 'beds' =>6, 'bed_type' =>3, 'bathrooms' =>2.0, 'amenities' =>'2,3,5,6,7,10,11,12,13,15,22,23,24,27,28,29', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-08 01:26:43', 'updated_at' =>'2016-02-08 01:34:14', 'deleted_at' =>NULL],
                ['id' => 10007 , 'user_id' => 10001, 'name' => 'Beautiful brownstone room','sub_name' =>'Private room in New York', 'summary' =>'Beautiful brownstone room is located in the center of Brooklyn, where everything is is possible . Good delicious , spicey food ,a friendly rainbow mixture of all races , Brooklyn botanical garden , prospect park , Brooklyn children Museum', 'property_type' =>2, 'room_type' =>2, 'accommodates' =>12, 'bedrooms' =>4, 'beds' =>6, 'bed_type' =>3, 'bathrooms' =>2.0, 'amenities' =>'1,2,3,7,8,10,11,12,22,23,24,25,28,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 05:43:19', 'updated_at' =>'2016-02-11 05:48:08', 'deleted_at' =>NULL],
                ['id' => 10008 , 'user_id' => 10003, 'name' => 'Cozy Room in Brooklyn','sub_name' =>'Private room in New York', 'summary' =>'Small Room. Steps away from the 3 train. A few short blocks from Franklin Ave which has tons of great restaurants and bars. Walking distance to Prospect Park and Botanical gardens.', 'property_type' =>3, 'room_type' =>2, 'accommodates' =>12, 'bedrooms' =>4, 'beds' =>8, 'bed_type' =>3, 'bathrooms' =>2.5, 'amenities' =>'1,2,3,7,8,10,11,12,22,23,24,25,28,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 05:52:21', 'updated_at' =>'2016-02-11 05:56:38', 'deleted_at' =>NULL],
                ['id' => 10009 , 'user_id' => 10002, 'name' => 'Cozy room in center of Park Slope','sub_name' =>'Entire home/apt in New York', 'summary' =>'Cozy air conditioned room in owner occupied house in the heart of Park Slope. Shared bathroom with shower/bath tub. Steps away from restaurants/bars and shopping. Within walking distance of major subway lines, Prospect Park, BAM and Barclay Center.', 'property_type' =>3, 'room_type' =>1, 'accommodates' =>9, 'bedrooms' =>5, 'beds' =>8, 'bed_type' =>2, 'bathrooms' =>2.5, 'amenities' =>'3,4,5,7,10,12,13,14,22,23,24,27,28,29', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 05:57:24', 'updated_at' =>'2016-02-11 06:01:05', 'deleted_at' =>NULL],
                ['id' => 10010 , 'user_id' => 10002, 'name' => 'Chambre accueillante chezl habitant','sub_name' =>'Entire home/apt in Paris', 'summary' =>'Chambre dans un appartement en hauteur, 7 min du métro Marcel Sembat L9, idéale pour un passage à Paris. L appartement dispose d une salle de bain, wc, cuisine et un salon à votre disposition, à partager avec nous (Anna, Alex, 30 ans et Biscotte, petit carlin de 2 ans). Nous nous ferons une joie de vous accueillir chez nous et de répondre à toutes vos questions et curiosités :)', 'property_type' =>2, 'room_type' =>1, 'accommodates' =>8, 'bedrooms' =>4, 'beds' =>6, 'bed_type' =>5, 'bathrooms' =>2.0, 'amenities' =>'3,4,6,7,10,11,12,14,21,23,24,25,27,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 06:34:08', 'updated_at' =>'2016-02-11 06:37:00', 'deleted_at' =>NULL],
                ['id' => 10011 , 'user_id' => 10003, 'name' => 'CHAMPS ELYSEES APARTMENT','sub_name' =>'Private room in Paris', 'summary' =>'A very nice, luminous and design loft that was entirely refurbished in 2015, located in the heart of Saint-Germain-des-Prés, at 100m of Jardin du Luxembourg. The appartment is located on the 1st floor of a traditional Parisian building.', 'property_type' =>1, 'room_type' =>2, 'accommodates' =>11, 'bedrooms' =>4, 'beds' =>5, 'bed_type' =>2, 'bathrooms' =>2.0, 'amenities' =>'2,3,4,5,11,12,13,16,17,21,22,27,28,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 06:37:44', 'updated_at' =>'2016-02-11 06:43:45', 'deleted_at' =>NULL],
                ['id' => 10012 , 'user_id' => 10002, 'name' => 'Charming Studio Ile Saint-Louis','sub_name' =>'Shared room in Paris', 'summary' =>'First choice location in the very heart of Paris. Enjoy this welcoming studio fully equipped to cater to your needs. Featuring a large living area with double sofa bed, an open kitchen and a shower room with toilet. Ideal for a romantic stay in Paris', 'property_type' =>3, 'room_type' =>3, 'accommodates' =>9, 'bedrooms' =>4, 'beds' =>8, 'bed_type' =>3, 'bathrooms' =>3.5, 'amenities' =>'1,2,4,5,6,11,12,13,16,17,18,22,23,24,25,27,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 06:45:05', 'updated_at' =>'2016-02-11 06:47:54', 'deleted_at' =>NULL],
                ['id' => 10013 , 'user_id' => 10001, 'name' => 'Haleakala B&B-Aloha Rm / Prvt Entry','sub_name' =>'Private room in New York', 'summary' =>'Haleakala Bed & Breakfast is surrounded by Macadamia Orchards and Coffee groves providing a natural setting for many of Hawaii birds and game fowl. You will enjoy the unfettered views of the Western Pacific Ocean & Sunsets from the Main Lanai.', 'property_type' =>1, 'room_type' =>2, 'accommodates' =>7, 'bedrooms' =>3, 'beds' =>5, 'bed_type' =>3, 'bathrooms' =>2.5, 'amenities' =>'1,2,4,5,6,11,12,13,15,17,21,23,24,26,27,28,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>NULL, 'created_at' =>'2016-02-11 06:58:13', 'updated_at' =>'2016-02-11 07:02:52', 'deleted_at' =>NULL],
                ['id' => 10014 , 'user_id' => 10004, 'name' => 'I "loooft" Barcelona!','sub_name' =>'Entire home/apt in Barcelona', 'summary' =>'This light room-loft is perfect for couples or single travelers who love terraces and opened air. Ideal for those who value space and quality with a competitive price.', 'property_type' =>2, 'room_type' =>1, 'accommodates' =>5, 'bedrooms' =>4, 'beds' =>7, 'bed_type' =>2, 'bathrooms' =>2.0, 'amenities' =>'1,4,5,7,8,10,11,12,14,15,21,22,23,28,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 07:10:08', 'updated_at' =>'2016-02-11 07:13:53', 'deleted_at' =>NULL],
                ['id' => 10015 , 'user_id' => 10001, 'name' => 'Studio with lake view','sub_name' =>'Private room in Berlin', 'summary' =>'Studio with view at Lake Rummelsburg and the Skyline of Berlin, including the TV tower. There are two convenient sofa beds for three people and a lot of space for sleeping mats…\nIMPORTANT: The office must be possible to use occasionally!', 'property_type' =>2, 'room_type' =>2, 'accommodates' =>6, 'bedrooms' =>4, 'beds' =>5, 'bed_type' =>4, 'bathrooms' =>3.5, 'amenities' =>'1,2,3,7,8,10,11,12,16,17,23,24,25,28,29,30', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 07:20:48', 'updated_at' =>'2016-02-11 07:25:03', 'deleted_at' =>NULL],
                ['id' => 10016 , 'user_id' => 10003, 'name' => 'Elegant studio near by the castle','sub_name' =>'Private room in Budapest', 'summary' =>'Be a downtown citizen of Budapest for a little time!:)Come and learn more about the Budapest mainstream lifestyle in this built in 1910 house.The studio has got a rustically elegant design,and its a comfortable,quiet home in the center', 'property_type' =>3, 'room_type' =>2, 'accommodates' =>5, 'bedrooms' =>5, 'beds' =>6, 'bed_type' =>4, 'bathrooms' =>2.5, 'amenities' =>'1,2,3,6,7,10,11,14,15,17,18,21,23,24,28,29,31', 'calendar_type' =>'Always' , 'started' =>'Yes', 'popular' =>'Yes', 'status' =>'Listed', 'created_at' =>'2016-02-11 07:34:04', 'updated_at' =>'2016-02-11 07:37:37', 'deleted_at' =>NULL]
        	]);
    }
}


                
                
